version: "3.8"
services:
  db:
    image: drscripts/postgres-cube-patch:16.2
    container_name: pg-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mejik
      POSTGRES_PASSWORD: 2wsx1qaz
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2wsx1qaz
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  cache:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 2wsx1qaz
    volumes: 
      - cache:/data
volumes:
  local_pgdata:
  pgadmin-data:
  cache:
