start:
	docker compose -p pg-cube-patch up -d
build:
	docker compose -p pg-cube-patch build
clean:
	docker compose -p pg-cube-patch down
stop:
	docker compose -p pg-cube-patch stop
push:
	docker compose -p pg-cube-patch push
